### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by mahendaraReddy** [xvik/guice-persist-orient#11]
can any body tell me how to configure guice for orientdb with spring boot

**Comment by xvik** [comment]
Spring-boot is obviously using spring and not guice (which is required by guice-persist-orient).
You can try to merry spring with guice https://github.com/spring-projects/spring-guice.
But almost certainly it's a bad idea.

You should look for integration library for spring or better for spring-data (like https://github.com/orientechnologies/spring-data-orientdb).

If you still want guice, then it's better to look to dropwizard (http://dropwizard.io). 
I'm using it with my own guice integration: https://github.com/xvik/dropwizard-guicey.
