### ISSUE TITLE
Question: How do I register my custom types serializer with guice-persist-orient

### ISSUE THREAD

**Issue by sblommers** [xvik/guice-persist-orient#14]
I am consuming some CXF generated WebService and have XMLGregorianCalendar as XMLElement type. I need to register a custom serializer for this class. The description on how to do this is here [http://orientdb.com/docs/2.2/Object-2-Record-Java-Binding.html#custom-types](http://orientdb.com/docs/2.2/Object-2-Record-Java-Binding.html#custom-types)

````
OObjectSerializerContext serializerContext = new OObjectSerializerContext();
serializerContext.bind(new OObjectSerializer<XMLGregorianCalendar, Long>() {
	@Override
	public Object serializeFieldValue(Class<?> iClass, XMLGregorianCalendar iFieldValue) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object unserializeFieldValue(Class<?> iClass, Long iFieldValue) {
		// TODO Auto-generated method stub
		return null;
	}
}, database?);
````

Is there a way to register?

Update: I am able to use jaxb:bindings to generate different property types and use adapters to fix this but I wanted to try and do it the naive way first.

**Comment by xvik** [comment]
Hi! 
Custom type must be registered before model registration so the best candidate to hook in is SchemeInitializer. 

Basic idea: extend one of default initializers to register custom type before model initialization. It wasn't intended to be customized like this, so the implementation may look clumsy, but still there are not much code required. 

I did sample test that shows custom type usage: https://github.com/xvik/guice-persist-orient/commit/4ad81d19c8252651aa2f2f16026e91fa5b4b0830

I will think about more natural support for custom types

**Comment by sblommers** [comment]
Thanks a lot, exactly what I was looking for, awesome!

**Comment by sblommers** [comment]
Thanks for releasing 3.3.0 !!
