### ISSUE TITLE
Repository query: boolean parameter not supported?

### ISSUE THREAD

**Issue by gutsverwalter** [xvik/guice-persist-orient#6]
Dear Vyacheslav, 

maybe I did something wrong, but the following is not working for me:

@Query("select from User where username = ? and active = ? limit 1")
 User findByUsernameAndActive(String username, boolean active);

It will always return null, if I call it with a username that exists and active == true, even if the user is set active in the database. 
If I remove the boolean parameter, it works. (with non-primitive Boolean it also doesn't work)

Maybe you could take a look at this sometime, but it's not urgent - thank you!

**Comment by xvik** [comment]
It's a regression for orient 2.1. In 2.0.10 it works [proof test](https://github.com/xvik/guice-persist-orient/blob/master/src/test/groovy/ru/vyarus/guice/persist/orient/study/boolparam/BoolParamTest.groovy)

I created new issue https://github.com/orientechnologies/orientdb/issues/4224

As a workaround you can use named parameters:
```java
@Query("select from User where username = :name and active = :active limit 1")
User findByUsernameAndActive(@Param("name") String username, @Param("active") boolean active);
```
